### ISSUE TITLE
Code Review

### ISSUE THREAD

**Issue by Ruhul-Quddus-Tamim** [mhasan502/senheng-scraping#1]
- Hi there, I've reviewed your code, your attempt was good enough within two days. What I can understand from your script is that you have used selenium web driver gecko to scrape the data automatically.

- Understand that you have this as a parser argument for automated testing so no GUI and improved performance:
 ```
options.add_argument('--headless')
 cls._instance = webdriver.Chrome(options=options)
```
- What I think is that in the long term this solution might not be sustainable because I cannot be able to see that all the data have been pulled into the csv, for example, mobile category, I can only see 100 rows, but there should more than 100 rows, around ~114 rows and for some rows there are missing prices. I suspect that it couldn't be able pull all the data is because somehow your script crashed/failed after sometimes of scraping it using the `WebDriver`.

Appreciate your works and the way of using CI/CD github workflows, separating the modules using class and methods following the best software engineering practises.

We will call you for another interview session with our Management team soon. Thanks!

**Comment by mhasan502** [comment]
Hi @Ruhul-Quddus-Tamim 

There are some missing data on the website. Some products show on product pages, but if you click on them, they return **404**. Putting on a position to discard the product, which I did. 

For example, the third item on [mobile and tablets page](https://www.senheng.com.my/all-products/mobiles-tablets.html)

![image](https://github.com/mhasan502/senheng-scraping/assets/22940197/c29c5de7-e502-446e-9260-378d75299aec)
![image](https://github.com/mhasan502/senheng-scraping/assets/22940197/cc8819ea-9858-41c6-ab29-c310eaa75019)
